# fly.toml app configuration file generated for lf-web on 2023-09-18T20:36:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lf-web"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  SESSION_COOKIE_DOMAIN = "lf-web.fly.dev"
  SESSION_COOKIE_NAME = "lfweb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
