name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: |
          3.11
          3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Analysing the code with pylint
      run: |
        poetry run pylint --fail-under=9 $(git ls-files '*.py')
    - name: Black validation
      run: |
        poetry run black --check .
    - name: Test code
      env:
        REDIS_HOST: redis
        API_USERNAME: ${{ secrets.API_USERNAME }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
        API_BASE_URL: ${{ vars.API_BASE_URL }}
        API_VERSION: ${{ vars.API_VERSION }}
        API_MEMBERS_API: ${{ vars.API_MEMBERS_API }}
        API_ACTIVITIES_API: ${{ vars.API_ACTIVITIES_API }}
      run: |
        echo "REDIS_HOST: $REDIS_HOST"
        echo "API_MEMBERS_API: $API_MEMBERS_API"
        poetry run pytest .
    services:
      # Add a redis container as a service for the pytest job
      redis:
        image: redis
        